version: "3.7"
services:
    web:
        build: ./finalblog
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./finalblog/:/usr/src/finalblog/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=django
            - POSTGRES_PASSWORD=1111
            - POSTGRES_DB=finalblog
volumes:
    postgres_data: