version: "3.7"
services:
    web:
        image: moskalev/mysite
#        build:
#            context: ./finalblog
#            dockerfile: Dockerfile.prod
        command: gunicorn finalblog.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/finalblog/web/static
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    nginx:
        image: moskalev/mysite-nginx
#        build: ./nginx
        volumes:
            - static_volume:/home/finalblog/web/static
        ports:
            - 1337:80
        depends_on:
            - web
volumes:
    postgres_data:
    static_volume:
    media_volume:

